# mint/bash_profile

# Fix the key-bindings and add support for Ukrainain
# US-dvorak/Ukrainian switching by pressing both shift keys together
setxkbmap -layout "us,ua" -variant "dvorak,winkeys"
setxkbmap -option grp:shifts_toggle
xmodmap ~/.Xmodmap
